//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcular.
        /// </summary>
        internal static string btnCalcular {
            get {
                return ResourceManager.GetString("btnCalcular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar.
        /// </summary>
        internal static string btnLimpar {
            get {
                return ResourceManager.GetString("btnLimpar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.06257.
        /// </summary>
        internal static string dollar {
            get {
                return ResourceManager.GetString("dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testes.
        /// </summary>
        internal static string gbTestes {
            get {
                return ResourceManager.GetString("gbTestes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trab. Práticos.
        /// </summary>
        internal static string gbTrabPraticos {
            get {
                return ResourceManager.GetString("gbTrabPraticos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 117.80.
        /// </summary>
        internal static string iene {
            get {
                return ResourceManager.GetString("iene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nota final é:.
        /// </summary>
        internal static string lblMediaFinal {
            get {
                return ResourceManager.GetString("lblMediaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1º Teste.
        /// </summary>
        internal static string lblTeste1 {
            get {
                return ResourceManager.GetString("lblTeste1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2º Teste.
        /// </summary>
        internal static string lblTeste2 {
            get {
                return ResourceManager.GetString("lblTeste2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1º Trab. Prático.
        /// </summary>
        internal static string lblTrab1 {
            get {
                return ResourceManager.GetString("lblTrab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2º Trab. Prático.
        /// </summary>
        internal static string lblTrab2 {
            get {
                return ResourceManager.GetString("lblTrab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabalho Final.
        /// </summary>
        internal static string lblTrabFinal {
            get {
                return ResourceManager.GetString("lblTrabFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.85263.
        /// </summary>
        internal static string libra {
            get {
                return ResourceManager.GetString("libra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.65.
        /// </summary>
        internal static string peso1 {
            get {
                return ResourceManager.GetString("peso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.15.
        /// </summary>
        internal static string peso2 {
            get {
                return ResourceManager.GetString("peso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.20.
        /// </summary>
        internal static string peso3 {
            get {
                return ResourceManager.GetString("peso3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.79447.
        /// </summary>
        internal static string sek {
            get {
                return ResourceManager.GetString("sek", resourceCulture);
            }
        }
    }
}
